name: Snowflake Database Migrations

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install schemachange
      run: |
        pip install --upgrade pip
        pip install schemachange==4.0.1
        
    - name: Create connections.toml
      run: |
        cat > connections.toml << EOF
        [connections.default]
        account = "${{ secrets.SF_ACCOUNT }}"
        user = "${{ secrets.SF_USERNAME }}"
        password = "${{ secrets.SF_PASSWORD }}"
        warehouse = "${{ secrets.SF_WAREHOUSE }}"
        database = "${{ secrets.SF_DATABASE }}"
        schema = "${{ secrets.SF_SCHEMA }}"
        EOF
        echo "Created connections.toml file"
        ls -la connections.toml
        
    - name: Run schemachange
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Running schemachange deploy..."
        schemachange deploy \
          --root-folder migrations \
          --verbose