name: Deploy to Snowflake

on:
  push:
    branches:
      - main  # or master, adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install schemachange
      run: pip install schemachange

    - name: Create .config directory
      run: mkdir -p .config

    - name: Create connections.toml with secrets
      run: |
        cat > .config/connections.toml <<EOF
        [connections.dev]
        account = "${{ secrets.SF_ACCOUNT }}"
        user = "${{ secrets.SF_USER }}"
        password = "${{ secrets.SF_PASSWORD }}"
        role = "${{ secrets.SF_ROLE }}"
        warehouse = "${{ secrets.SF_WAREHOUSE }}"
        database = "${{ secrets.SF_DATABASE }}"
        schema = "${{ secrets.SF_SCHEMA }}"
        EOF
    
    - name: Show connections.toml content
      run: cat .config/connections.toml


    - name: Run schemachange migrations
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
      run: |
        schemachange --config-folder .config --connection-name dev --create-change-history-table

    - name: List files for debugging
      run: ls -R
