name: Deploy to Snowflake

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print initial working directory and contents
        run: |
          pwd
          ls -al

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python version & path sanity check
        run: |
          python --version
          which python

      - name: Install schemachange
        run: pip install schemachange

      - name: Show schemachange version
        run: schemachange --version

      - name: Create .config directory
        run: mkdir -p .config

      - name: Verify .config directory exists
        run: ls -al .config

      - name: Create connections.toml with GitHub Secrets
        run: |
          cat > .config/connections.toml <<EOF
          [connections.dev]
          account = "${{ secrets.SF_ACCOUNT }}"
          user = "${{ secrets.SF_USER }}"
          password = "${{ secrets.SF_PASSWORD }}"
          role = "${{ secrets.SF_ROLE }}"
          warehouse = "${{ secrets.SF_WAREHOUSE }}"
          database = "${{ secrets.SF_DATABASE }}"
          schema = "${{ secrets.SF_SCHEMA }}"
          EOF

      - name: Print working directory and .config after creating TOML
        run: |
          pwd
          ls -al
          ls -al .config

      - name: Show connections.toml contents (for debug; redact password in log if sensitive)
        run: cat .config/connections.toml

      - name: Run schemachange migrations (with verbose/debug)
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          schemachange --config-folder .config --connection-name dev --create-change-history-table -v

      - name: Final directory listing for troubleshooting
        run: ls -lR