name: Deploy to Snowflake

on:
  push:
    branches:
      - main  # Or 'master' based on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install schemachange
      run: pip install schemachange

    - name: Run schemachange
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
      run: |
        schemachange --config-folder . \
                    --connection-name dev \
                    --create-change-history-table


