name: Deploy to Snowflake

on:
  push:
    branches:
      - main  # Or 'master' based on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install schemachange
      run: pip install schemachange

    - name: Run schemachange
      run: |
        schemachange -f ./migrations \
          -a ${{ secrets.SF_ACCOUNT }} \
          -u ${{ secrets.SNOWFLAKE_USER }} \
          -p ${{ secrets.SF_PASSWORD }} \
          -r ${{ secrets.SF_ROLE }} \
          -w ${{ secrets.SF_WAREHOUSE }} \
          -d ${{ secrets.SF_DATABASE }} \
          -c PUBLIC \
          --create-change-history-table

