name: Deploy to Snowflake

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print initial working directory and contents
        run: |
          pwd
          ls -al

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Verify Python version & path
        run: |
          python --version
          which python

      - name: Install schemachange
        run: pip install schemachange

      - name: Show schemachange help (avoid --version error)
        run: schemachange deploy --help

      - name: Create .config directory
        run: mkdir -p .config

      - name: Verify .config directory exists
        run: ls -al .config

      - name: Create connections.toml with GitHub Secrets (no indentation!)
        run: |
          cat > .config/connections.toml <<EOF
          [connections.dev]
          account = "${{ secrets.SF_ACCOUNT }}"
          user = "${{ secrets.SF_USER }}"
          password = "${{ secrets.SF_PASSWORD }}"
          role = "${{ secrets.SF_ROLE }}"
          warehouse = "${{ secrets.SF_WAREHOUSE }}"
          database = "${{ secrets.SF_DATABASE }}"
          schema = "${{ secrets.SF_SCHEMA }}"
          EOF

      - name: Show connections.toml content for debug (password masked in logs by GitHub)
        run: cat .config/connections.toml

      - name: Check file encoding and BOM presence
        run: |
          file .config/connections.toml
          xxd .config/connections.toml | head -8

      - name: Run schemachange migrations with verbose output
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          schemachange --config-folder .config --connection-name dev --create-change-history-table -v

      - name: Final recursive directory listing for troubleshooting
        run: ls -lR